import type { Job } from "@/features/jobs/types";

// 本来はバックエンド（Laravel/CakePHP など）の API から取得する想定のモックデータ
export const jobs: Job[] = [
  {
    id: "1001",
    title: "フロントエンドエンジニア（Next.js）",
    company: "株式会社サンプルテック",
    category: "engineer",
    location: "東京都渋谷区",
    remote: true,
    salaryMin: 550,
    salaryMax: 850,
    skills: ["Next.js", "TypeScript", "CSS"],
    description:
      "自社メディアのフロントエンド開発をお任せします。App Router への移行プロジェクトをリードいただきます。",
    publishedAt: "2026-09-14",
  },
  {
    id: "1002",
    title: "バックエンドエンジニア（PHP/Laravel）",
    company: "株式会社ミライHR",
    category: "engineer",
    location: "東京都港区",
    remote: false,
    salaryMin: 500,
    salaryMax: 800,
    skills: ["PHP", "Laravel", "MySQL"],
    description: "求人プラットフォームの API 開発。CakePHP からのリプレイスを進めています。",
    publishedAt: "2026-09-13",
  },
  {
    id: "1003",
    title: "UI/UXデザイナー",
    company: "株式会社デザインラボ",
    category: "creator",
    location: "大阪府大阪市",
    remote: true,
    salaryMin: 450,
    salaryMax: 700,
    skills: ["Figma", "デザインシステム"],
    description: "SaaS プロダクトの UI 設計とデザインシステムの整備を担当。",
    publishedAt: "2026-09-12",
  },
  {
    id: "1004",
    title: "ゲームプランナー（スマホRPG）",
    company: "株式会社プレイワークス",
    category: "game",
    location: "東京都新宿区",
    remote: false,
    salaryMin: 400,
    salaryMax: 650,
    skills: ["企画", "Unity"],
    description: "運営中タイトルのイベント企画・レベルデザイン。",
    publishedAt: "2026-09-11",
  },
  {
    id: "1005",
    title: "Webマーケター（SEO/広告）",
    company: "株式会社グロースパートナーズ",
    category: "marketing",
    location: "東京都千代田区",
    remote: true,
    salaryMin: 450,
    salaryMax: 750,
    skills: ["SEO", "Google Analytics", "WordPress"],
    description: "オウンドメディアの集客戦略立案と改善施策の実行。",
    publishedAt: "2026-09-10",
  },
  {
    id: "1006",
    title: "テックリード（React/TypeScript）",
    company: "株式会社クラウドフォース",
    category: "engineer",
    location: "福岡県福岡市",
    remote: true,
    salaryMin: 750,
    salaryMax: 1100,
    skills: ["React", "TypeScript", "Storybook", "GraphQL"],
    description: "フロントエンドチーム（6名）の技術リード。テスト戦略の策定も担当。",
    publishedAt: "2026-09-09",
  },
  {
    id: "1007",
    title: "3DCGデザイナー",
    company: "株式会社プレイワークス",
    category: "game",
    location: "東京都新宿区",
    remote: false,
    salaryMin: 420,
    salaryMax: 680,
    skills: ["Maya", "Blender"],
    description: "家庭用ゲームのキャラクターモデリング。",
    publishedAt: "2026-09-08",
  },
  {
    id: "1008",
    title: "SRE / インフラエンジニア",
    company: "株式会社サンプルテック",
    category: "engineer",
    location: "東京都渋谷区",
    remote: true,
    salaryMin: 650,
    salaryMax: 950,
    skills: ["AWS", "Terraform", "Kubernetes"],
    description: "大規模トラフィックを支えるインフラの設計・運用。",
    publishedAt: "2026-09-07",
  },
  {
    id: "1009",
    title: "Webデザイナー（コーディング有）",
    company: "株式会社デザインラボ",
    category: "creator",
    location: "リモート",
    remote: true,
    salaryMin: 380,
    salaryMax: 550,
    skills: ["HTML", "CSS", "WordPress"],
    description: "LP・コーポレートサイトのデザインとコーディング。",
    publishedAt: "2026-09-06",
  },
  {
    id: "1010",
    title: "CRMマーケター",
    company: "株式会社ミライHR",
    category: "marketing",
    location: "東京都港区",
    remote: false,
    salaryMin: 480,
    salaryMax: 720,
    skills: ["MA", "SQL"],
    description: "会員向けメール・プッシュ施策の設計と効果検証。",
    publishedAt: "2026-09-05",
  },
  {
    id: "1011",
    title: "フルスタックエンジニア（Next.js/Laravel）",
    company: "株式会社グロースパートナーズ",
    category: "engineer",
    location: "東京都千代田区",
    remote: true,
    salaryMin: 600,
    salaryMax: 900,
    skills: ["Next.js", "Laravel", "TypeScript"],
    description: "新規 SaaS をフロントからバックエンドまで一気通貫で開発。",
    publishedAt: "2026-09-04",
  },
  {
    id: "1012",
    title: "QAエンジニア（E2Eテスト）",
    company: "株式会社クラウドフォース",
    category: "engineer",
    location: "福岡県福岡市",
    remote: true,
    salaryMin: 450,
    salaryMax: 700,
    skills: ["Playwright", "Vitest"],
    description: "テスト自動化基盤の構築と品質改善。",
    publishedAt: "2026-09-03",
  },
];
